### PR TITLE
Create initial unit tests

### LINKED ISSUE #21: create initial unit tests/regression tests
We need regression test(s) for the current state of the schedule generator, at least just for the current year's events.

### PR DESCRIPTION
**Pull request by basil96**
This is a reorganized file structure that's best for packaging when we get to it.
A few stepwise small commits are included that deal with making text encodings and line endings consistent.

### CODE REVIEW

**Review by scliddle — CHANGES_REQUESTED** [review]
I expected a pytest.ini with some markers in it and maybe a section like this. Maybe we don't need it if it runs by default. 

[pytest]
python_files = test_*.py

This isn't necessary, but adding requests to requirements-test.txt is.
Also, please add a readme.txt file that explains how to run the tests.

**Comment by basil96** [comment]
Oops, fixed.

**Review by scliddle — APPROVED** [review]
Works great, thanks for the education on .pth files

Nice work.

**Comment by basil96** [comment]
Just dotting the i's and crossing the t's in imports.

**Comment by scliddle** [comment]
I did not do the merge because I assumed you wanted to squash. Please merge at will @basil96

**Review by scliddle — APPROVED** [review]

**Pull request merged**
